---
- name: create new playbook directory
  file: path="{{new_playbook_path}}/{{new_playbook_name}}" state=directory

- name: create directory structure
  synchronize: src={{ role_path }}/files/skeleton/ dest="{{new_playbook_path}}/{{new_playbook_name}}/"

- name: add licence file
  template: src=LICENSE.j2 dest="{{ new_playbook_path }}/{{new_playbook_name}}/LICENSE"

- name: add README file
  template: src=README.j2 dest="{{ new_playbook_path }}/{{new_playbook_name}}/README.md"

- name: add ansible.cfg
  template: src=ansible.cfg.j2 dest="{{ new_playbook_path }}/{{new_playbook_name}}/ansible.cfg"
